# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7cf7042e197b84b1b8b0b2d7f7bc4647acb9869c77cb8cfc43884853adc125e3577b90b1d8fd6ab57d023c544683adcb54f4fa5e6caba07ef3ab8275a05318

test:
  secret_key_base: da66d8d01bd918a5839ec71ddc6134e19cac969ec7941a66409dc5405698dfa6e2961b3344123b50c3c72bda1c029fdaee39d1382999b4b2020e6e065ab56742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
